<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_transaction' => [['id'], ['_controller' => 'App\\Controller\\TransactionController::getTransaction'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/transaction']], [], [], []],
    'app_user_getbalance' => [['id'], ['_controller' => 'App\\Controller\\UserController::getBalance'], [], [['text', '/balance'], ['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], [], []],
];
